----------------------------------------------
-- Profession Shopping List: AprilFools.lua --
----------------------------------------------
-- Disclaimer: the code in this file was generated by ChatGPT.

local appName, app = ...
local api = app.api
local L = app.locales

-------------
-- ON LOAD --
-------------

app.Event:Register("PLAYER_ENTERING_WORLD", function(isInitialLogin, isReloadingUi)
	local date = C_DateAndTime.GetCurrentCalendarTime()
	if date.month == 4 and date.monthDay == 1 then
		app.Flag.AprilFools = true
	end
end)

-------------
-- GRAVITY --
-------------

app.Gravity = {}
app.Gravity.gravity = 1800
app.Gravity.friction = 1200
app.Gravity.bounce = 0.35
app.Gravity.ceilingBounce = 0.25
app.Gravity.minBounceVelocity = 100

app.Gravity.velocityX = 0
app.Gravity.velocityY = 0
app.Gravity.falling = false

app.Gravity.posX = 0
app.Gravity.posY = 0

app.Gravity.dragging = false
app.Gravity.lastX = 0
app.Gravity.lastY = 0
app.Gravity.lastTime = 0

function app.Gravity:StartGravity(frame, velocityX, velocityY)
	if not app.Flag.AprilFools then return end

	self.posX = frame:GetLeft()
	self.posY = frame:GetBottom()
	self.velocityX = velocityX or 0
	self.velocityY = velocityY or 0
	self.falling = true

	frame:SetScript("OnUpdate", function(self, elapsed)
		if not app.Gravity.falling then return end

		-- Gravity
		app.Gravity.velocityY = app.Gravity.velocityY - app.Gravity.gravity * elapsed

		-- Horizontal friction
		if app.Gravity.velocityX > 0 then
			app.Gravity.velocityX = math.max(0, app.Gravity.velocityX - app.Gravity.friction * elapsed)
		elseif app.Gravity.velocityX < 0 then
			app.Gravity.velocityX = math.min(0, app.Gravity.velocityX + app.Gravity.friction * elapsed)
		end

		-- Move
		app.Gravity.posX = app.Gravity.posX + app.Gravity.velocityX * elapsed
		app.Gravity.posY = app.Gravity.posY + app.Gravity.velocityY * elapsed

		-- Screen dimensions
		local screenWidth = UIParent:GetWidth()
		local screenHeight = UIParent:GetHeight()
		local frameWidth = self:GetWidth()
		local frameHeight = self:GetHeight()

		-- Bottom collision
		if app.Gravity.posY <= 0 then
			app.Gravity.posY = 0

			if math.abs(app.Gravity.velocityY) > app.Gravity.minBounceVelocity then
				app.Gravity.velocityY = math.abs(app.Gravity.velocityY) * app.Gravity.bounce
			else
				app.Gravity.velocityY = 0
				app.Gravity.falling = false
			end
		end

		-- Ceiling collision
		local maxY = screenHeight - frameHeight

		if app.Gravity.posY >= maxY then
			app.Gravity.posY = maxY

			if math.abs(app.Gravity.velocityY) > app.Gravity.minBounceVelocity then
				app.Gravity.velocityY = -math.abs(app.Gravity.velocityY) * app.Gravity.ceilingBounce
			else
				app.Gravity.velocityY = 0
			end
		end

		-- Horizontal collisions
		local screenWidth = UIParent:GetWidth()
		local frameWidth = self:GetWidth()

		-- Left wall
		if app.Gravity.posX <= 0 then
			app.Gravity.posX = 0

			if app.Gravity.velocityX < 0 then
				app.Gravity.velocityX = math.abs(app.Gravity.velocityX) * app.Gravity.bounce
			end
		end

		-- Right wall
		local maxX = screenWidth - frameWidth

		if app.Gravity.posX >= maxX then
			app.Gravity.posX = maxX

			if app.Gravity.velocityX > 0 then
				app.Gravity.velocityX = -math.abs(app.Gravity.velocityX) * app.Gravity.bounce
			end
		end

		-- Update frame position
		self:ClearAllPoints()
		self:SetPoint("BOTTOMLEFT", UIParent, "BOTTOMLEFT", app.Gravity.posX, app.Gravity.posY)

		if not app.Gravity.falling then
			self:SetScript("OnUpdate", nil)
		end
	end)
end

function app.Gravity:StartDragging(frame)
	if not app.Flag.AprilFools then return end

	self.dragging = true
	self.falling = false

	self.lastX = frame:GetLeft()
	self.lastY = frame:GetBottom()
	self.lastTime = GetTime()

	frame:SetScript("OnUpdate", function(self)
		if not app.Gravity.dragging then return end

		local now = GetTime()
		local x = self:GetLeft()
		local y = self:GetBottom()

		local elapsed = now - app.Gravity.lastTime

		if elapsed > 0 then
			app.Gravity.velocityX = (x - app.Gravity.lastX) / elapsed

			app.Gravity.velocityY = (y - app.Gravity.lastY) / elapsed
		end

		app.Gravity.lastX = x
		app.Gravity.lastY = y
		app.Gravity.lastTime = now
	end)
end


function app.Gravity:StopDragging(frame)
	if not app.Flag.AprilFools then return end

	self.dragging = false

	local velocityX = self.velocityX
	local velocityY = self.velocityY

	if math.abs(velocityX) < 10 then
		velocityX = 0
	end

	if math.abs(velocityY) < 10 then
		velocityY = 0
	end

	self:StartGravity(frame, velocityX, velocityY)
end
