name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Grab recipe itemIDs to recipeIDs
        run: git update-index --chmod=+x ./scripts/get-files.sh
             git update-index --chmod=+x ./scripts/convert-recipes-to-spell-ids.py
             bash ${GITHUB_WORKSPACE}/scripts/do-all.sh
